apiVersion: v1
kind: Pod
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
spec:
  containers:
  - name: kafka-zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
    - containerPort: 2181