apiVersion: v1
kind: Pod
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  containers:
  - name: kafka-ui
    image: provectuslabs/kafka-ui
    env:
    - name: KAFKA_CLUSTERS_0_NAME
      value: "local"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "kafka:9092"
    - name: KAFKA_CLUSTERS_0_ZOOKEEPER
      value: "kafka-zookeeper:32181"
    ports:
    - containerPort: 8080