---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express
spec:
  selector:
    app: mongodb-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-express
  labels:
    app: mongodb-express
spec:
  containers:
  - name: mongodb-express
    image: mongo-express
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    env:
    - name: ME_CONFIG_MONGODB_URL
      value: "mongodb://mongodb:27017"
    ports:
    - containerPort: 8081