apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: wums
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb-express
    image: mongo-express
    env:
    - name: ME_CONFIG_MONGODB_URL
      value: "mongodb://localhost:27017"
    ports:
    - containerPort: 8081
  - name: mongodb
    image: mongo
    ports:
    - containerPort: 27017