---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30004
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  containers:
  - name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    ports:
    - containerPort: 5601