---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: wums-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: wums-vs
spec:
  hosts:
  - "istio.wums"
  gateways:
  - wums-gateway
  http:
  - route:
    - destination:
        host: wums-gql
        port:
          number: 3001
