---
apiVersion: v1
kind: Service
metadata:
  name: wums-customer
spec:
  selector:
    app: wums-customer
  ports:
    - port: 8082
      targetPort: 8080
      nodePort: 30005
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: wums-customer
  labels:
    app: wums-customer
spec:
  containers:
  - name: wums-customer
    image: 251974498126.dkr.ecr.ap-northeast-2.amazonaws.com/wums-customer:1.4.0
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: regcred