apiVersion: v1
kind: Pod
metadata:
  name: wums-consumer
  labels:
    app: wums-consumer
spec:
  containers:
  - name: wums-consumer
    image: 251974498126.dkr.ecr.ap-northeast-2.amazonaws.com/wums-consumer:latest
    ports:
    - containerPort: 3000
  - name: wums-driver
    image: 251974498126.dkr.ecr.ap-northeast-2.amazonaws.com/wums-driver:latest
    ports:
    - containerPort: 5000
  imagePullSecrets:
  - name: regcred