---
apiVersion: v1
kind: Service
metadata:
  name: wums-gql
spec:
  selector:
    app: wums-gql
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30006
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: wums-gql
  labels:
    app: wums-gql
spec:
  containers:
  - name: wums-gql
    image: wums-gql
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: wums-gql-logs
      mountPath: /app/dist/logs
  volumes:
  - name: wums-gql-logs
    hostPath:
      path: /var/log/wums-gql