---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  containers:
  - name: kafka
    image: wurstmeister/kafka:latest
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    env:
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: "kafka"
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_PORT
      value: "9092"
    - name: KAFKA_CREATE_TOPICS
      value: "cursormonitoer:1:1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "kafka-zookeeper:2181"
    - name: BOOTSTRAP_SERVERS
      value: "kafka:9092"
    ports:
    - containerPort: 9092