---
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
spec:
  selector:
    app: kafka-zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
spec:
  containers:
  - name: kafka-zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
    - containerPort: 2181